import 'package:flutter/material.dart';
import 'package:zomato_flutter/models/meal.dart';
import './models/category.dart';

const DUMMY_VALUE = const [
  Category(
    id: 'c1',
    title: 'American',
    color: Colors.orange,
  ),
  Category(
    id: 'c2',
    title: 'Italian',
    color: Colors.yellow,
  ),
  Category(
    id: 'c3',
    title: 'chinese',
    color: Colors.purple,
  ),
  Category(
    id: 'c4',
    title: 'Asian',
    color: Colors.pinkAccent,
  ),
  Category(
    id: 'c5',
    title: 'Indian',
    color: Colors.green,
  ),
  Category(
    id: 'c6',
    title: 'Japanese',
    color: Colors.red,
  ),
  Category(
    id: 'c7',
    title: 'Thailands',
    color: Colors.pink,
  ),
  Category(
    id: 'c8',
    title: 'Bhramins',
    color: Colors.amber,
  ),
  Category(
    id: 'c9',
    title: 'Burmah',
    color: Colors.lightGreenAccent,
  ),
  Category(
    id: 'c10',
    title: 'Gujaraties',
    color: Colors.lightBlue,
  ),
];
const DUMMY_MEAL_VALUE = const [
  Meal(
      id: '1',
      categories: ['c1',],
      title: 'French Fries',
      imageUrl:
          'https://i2.wp.com/www.vegrecipesofindia.com/wp-content/uploads/2012/10/french-fries-recipe-1-1.jpg',
      ingredients: [
        'Potatoes',
        'Vegetable Oil (Canola Oil, Soybean Oil, Hydrogenated Soybean Oil, Natural Beef Flavor [Wheat and Milk Derivatives]*, Citric Acid [Preservative])',
        'Dextrose',
        'Sodium Acid Pyrophosphate (Maintain Color)',
        'Salt'
      ],
      steps: [
        'Cut the Potatoes',
        'Soak the Potatoes',
        'Drain and Dry the Potatoes',
        'Fry the Potatoes',
        'Drain and Cool the Half-Done Fries',
        'Fry the Potatoes Again',
        'Drain the Fries',
      ],
      duration: 15,
      complexity: Complexity.Simple,
      affordability: Affordability.Affordable,
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: true,
      isVegetarian: true),
  Meal(
    id: '2',
    categories: ['c2','c1'],
    title: 'Seafood pizza',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Seafood_pizza_%281%29.jpg/1024px-Seafood_pizza_%281%29.jpg',
    ingredients: [
      'Various seafood can be used to prepare the dish',
      'such as fish (including salmon, tuna, anchovy)',
      'shellfish',
      ' clams',
      'scallops',
      ' mussels',
      'shrimp,[3]' 'squid,[4]' 'lobster[5] and scungilli (sea snail)',
      '[6] among others',
    ],
    steps: [
      'Cut the Potatoes',
      'Soak the Potatoes',
      'Drain and Dry the Potatoes',
      'Fry the Potatoes',
      'Drain and Cool the Half-Done Fries',
      'Fry the Potatoes Again',
      'Drain the Fries',
    ],
    duration: 45,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: '3',
    categories: ['c3','c1'],
    title: 'chow mein ',
    imageUrl:
        'https://www.jessicagavin.com/wp-content/uploads/2018/01/chow-mein-5.jpg',
    ingredients: [
      'noodles are stir-fried with cabbage',
      'carrots',
      'bean sprouts',
      'green onions',
      'ginger and garlic for a flavorful vegetarian dish',
    ],
    steps: [
      'Cut the Potatoes',
      'Soak the Potatoes',
      'Drain and Dry the Potatoes',
      'Fry the Potatoes',
      'Drain and Cool the Half-Done Fries',
      'Fry the Potatoes Again',
      'Drain the Fries',
    ],
    duration: 30,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: '4',
    categories: ['c4'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://www.sauteedandbaked.com/wp-content/uploads/2017/01/Homemade-Chinese-Recipe-1024x965.jpg',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: '5',
    categories: ['c5'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://img1.rapidleaks.com/2018/09/best-indian-food.jpg',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: '6',
    categories: ['c6'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://ntvassets-a.akamaihd.net/BA383D664EE445949EE191D3222370F2.jpg',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: '7',
    categories: ['c7'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://theculturetrip.com/wp-content/uploads/2017/12/7794345124_f48e5b469c_k.jpg',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: false,
  ),
  Meal(
    id: '8',
    categories: ['c8'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://th.thgim.com/news/cities/Madurai/f8xvnn/article28804869.ece/alternates/FREE_435/25SMTOMATOJPGTHNAK',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: '9',
    categories: ['c9'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/6/64/Laphet_thoke.JPG',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: '10',
    categories: ['c10'],
    title: 'Chilli tofu stir-fry with soba noodles',
    imageUrl:
        'https://assets.traveltriangle.com/blog/wp-content/uploads/2018/02/Khandvi.jpg',
    ingredients: [
      '300g firm tofu, cut into 2cm pieces',
      '1 tablespoon sriracha or chilli sauce',
      '1/3 cup (80ml) salt-reduced soy sauce',
      '1 teaspoon sesame oil',
      '270g soba noodles',
      '1 tablespoon vegetable oil',
      '1 brown onion, thinly sliced',
      '1 bunch baby broccoli, halved lengthways',
      '200g green beans, halved',
      '1 long red chilli, thinly sliced (optional)',
    ],
    steps: [
      'Combine tofu, sriracha or chilli sauce, soy sauce and sesame oil in a bowl',
      'Cook the soba noodles in a large saucepan of boiling water for 4 mins or until tender. Drain well',
      'Heat vegetable oil in a wok or large frying pan over high heat. Drain tofu, reserving the marinade. Cook the tofu, in 2 batches, for 2 mins or until golden. Transfer to a bowl. Add onion to the wok or pan. Stir-fry for 3 mins or until tender. Add baby broccoli and beans. Stir-fry for 2 mins or until tender.',
      'Return the tofu to the wok or pan with noodles and reserved marinade. Stir-fry until the mixture is heated through. Divide among serving bowls and sprinkle with chilli, if using.',
    ],
    duration: 60,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
    isGlutenFree: true,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: false,
  ),
];
